INSERT IGNORE INTO `quests` (`id`, `user_id`, `is_custom`, `week`, `title`, `description`, `xp_reward`, `track`) VALUES
(100, NULL, 0, 7, 'Git Mission: selamatkan merge conflict', 'Simulasikan conflict di branch fitur, selesaikan tanpa menghapus kerjaan teman, dan push bersih.', 20, 'rpl'),
(101, NULL, 0, 8, 'API Project: REST mini produk', 'Bangun endpoint GET/POST produk dengan validasi dan response JSON konsisten + dokumentasi singkat.', 25, 'rpl'),
(102, NULL, 0, 8, 'Software Testing: unit test pertama', 'Tulis 5 unit test untuk fungsi register (valid + invalid), capai hijau semua di PHPUnit/Pest.', 20, 'rpl'),
(103, NULL, 0, 12, 'Capstone: aplikasi fullstack mini', 'Rilis aplikasi CRUD + auth + deploy + README profesional sebagai bukti magang.', 40, 'rpl'),
(110, NULL, 0, 1, 'IP Plan kantormu', 'Susun IP plan /24 untuk 3 divisi + gateway + DHCP scope di kertas/spreadsheet.', 15, 'tkj'),
(111, NULL, 0, 2, 'Install & hardening Ubuntu Server', 'Install Ubuntu Server di VM, buat user sudo, matikan login root, pasang UFW.', 20, 'tkj'),
(112, NULL, 0, 3, 'Bash: backup otomatis harian', 'Tulis skrip bash backup folder web + cron harian + uji restore satu file.', 20, 'tkj'),
(113, NULL, 0, 4, 'Crimping & uji kabel UTP', 'Crimping straight + cross, uji dengan LAN tester, catat hasil tiap kabel.', 15, 'tkj'),
(114, NULL, 0, 6, 'Web + file server untuk lab', 'Pasang Nginx + Samba di satu VM untuk dipakai satu lab komputer.', 25, 'tkj'),
(115, NULL, 0, 7, 'Sesi cloud: nyalakan VPS pertamamu', 'Provisioning VPS/EC2 termurah, SSH key-only, dan catat biaya per bulan.', 25, 'tkj'),
(116, NULL, 0, 9, 'Monitoring & log server', 'Pasang monitoring uptime + baca log auth untuk temukan percobaan login gagal.', 20, 'tkj'),
(117, NULL, 0, 12, 'Capstone: rancang jaringan lab', 'Gambar topologi + IP plan + daftar belanja untuk satu lab 20 PC sebagai proposal.', 40, 'tkj'),
(120, NULL, 0, 1, 'Brief pertamamu: redesain logo OSIS', 'Tulis ulang brief: tujuan, audiens, batasan, dan 3 kata kunci rasa desainnya.', 15, 'dkv'),
(121, NULL, 0, 2, 'Studi tipografi: pairing font', 'Pilih 1 font judul + 1 font isi, uji di poster A4 dan jelaskan alasannya.', 15, 'dkv'),
(122, NULL, 0, 4, 'Mini branding UMKM', 'Buat logo + palet 3 warna + kartu nama untuk satu UMKM di sekitarmu.', 25, 'dkv'),
(123, NULL, 0, 5, 'Wireframe aplikasi kasir', 'Gambar wireframe 5 layar alur kasir di kertas/Figma, fokus alur bukan warna.', 20, 'dkv'),
(124, NULL, 0, 8, 'UI hi-fi + prototipe klik', 'Ubah wireframe jadi UI berwarna + prototipe bisa diklik untuk demo ke teman.', 25, 'dkv'),
(125, NULL, 0, 9, 'Ilustrasi maskot kelas', 'Gambar maskot vektor + tampilkan di 3 ukuran (ikon, kaos, banner).', 20, 'dkv'),
(126, NULL, 0, 10, 'Motion: bumper 5 detik', 'Buat animasi pembuka 5 detik untuk video kelas dengan easing yang halus.', 20, 'dkv'),
(127, NULL, 0, 12, 'Capstone: portfolio + CV kreatif', 'Susun 5 karya terbaik + studi kasus singkat tiap karya + CV satu halaman.', 40, 'dkv');
